# Generated by Django 4.0.5 on 2022-06-18 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='korisnik',
            name='role',
            field=models.CharField(choices=[('adm', 'admin'), ('prof', 'profesor'), ('stu', 'student')], max_length=50),
        ),
    ]
